### ISSUE TITLE
Smart detection of --encode / --decode

### ISSUE THREAD

**Issue by charlesdaniels** [charlesdaniels/bitshuffle#1]
If neither `--encode` nor `--decode` are specified, then BitShuffle should attempt to select one based on a heuristic.

* If `--output` is specified, `--input` is `/dev/stdin`, and standard input is a tty, then we can infer the user want's to paste in BitShuffle packets and have them decoded, so we should thus infer `--decode`.
* If `--input` is specified, `--output` is not, then we can infer `--encode`, unless the input is standard in, and it is a tty.

Note that if no arguments are given to BitShuffle, then we should **not** infer anything, as we wouldn't want someone trying to find the help message to have a bunch of packets barfed all over their terminal.

**Comment by jyn514** [comment]
Added in https://github.com/charlesdaniels/bitshuffle/commit/998b11f51d9b73e10d70790aadd1ed30e9b23e47
