### ISSUE TITLE
Static builds for Windows/macOS/Linux/BSD

### ISSUE THREAD

**Issue by charlesdaniels** [charlesdaniels/bitshuffle#11]
In the interest of user friendliness, we should provide static builds for `RELEASE` versions of BitShuffle.

This can be accomplished using [PyInstaller](http://www.pyinstaller.org). I have personal experience with this tool and can handle producing the build scripts.

What remains unclear is how to actually produce the builds? We can certainly use TravisCI to run the build scripts, but I need to do some research on what getting build artifacts out of TravisCI looks like. Ideally, they would show up on the releases pages for any commit tagged with `X.Y.Z-RELEASE`.

**Comment by charlesdaniels** [comment]
Apparently TravisCI supports this as [GitHub Release Uploading](https://docs.travis-ci.com/user/deployment/releases/)

**Comment by jyn514** [comment]
Tried setting this up as documented in [your link](https://docs.travis-ci.com/user/deployment/releases/#Authenticating-with-an-OAuth-token), auth failed because I have two-factor turned on.

    joshua@debian-thinkpad:/usr/local/src/bitshuffle$ travis setup releases --force
    Username: jyn514@github.com
    Password for jyn514@github.com: ****************************************
    This API can only be accessed with username and password Basic Auth
    for a full error report, run travis report --org
    joshua@debian-thinkpad:/usr/local/src/bitshuffle$ travis report --org
    System
    Ruby:                     Ruby 2.3.3-p222
    Operating System:         Debian 9.2
    RubyGems:                 RubyGems 2.5.2.1

    CLI
    Version:                  1.8.8
    Plugins:                  none
    Auto-Completion:          yes
    Last Version Check:       2017-12-09 00:23:24 -0500

    Session
    API Endpoint:             https://api.travis-ci.org/
    Logged In:                no
    Verify SSL:               yes
    Enterprise:               no

    Endpoints
    org:                      https://api.travis-ci.org/ (current)

    Last Exception
    An error occurred running `travis setup --org`:
        RuntimeError: This API can only be accessed with username and password Basic Auth
            from /home/joshua/.gem/ruby/2.3.0/gems/travis-1.8.8/lib/travis/tools/github.rb:211:in `rescue in basic_auth'
            from /home/joshua/.gem/ruby/2.3.0/gems/travis-1.8.8/lib/travis/tools/github.rb:208:in `basic_auth'
            from /home/joshua/.gem/ruby/2.3.0/gems/travis-1.8.8/lib/travis/tools/github.rb:215:in `login'
            from /home/joshua/.gem/ruby/2.3.0/gems/travis-1.8.8/lib/travis/tools/github.rb:80:in `possible_tokens'
            from /home/joshua/.gem/ruby/2.3.0/gems/travis-1.8.8/lib/travis/tools/github.rb:49:in `each_token'
            from /home/joshua/.gem/ruby/2.3.0/gems/travis-1.8.8/lib/travis/tools/github.rb:36:in `with_token'
            from /home/joshua/.gem/ruby/2.3.0/gems/travis-1.8.8/lib/travis/cli/setup/releases.rb:12:in `block in run'
            from /home/joshua/.gem/ruby/2.3.0/gems/travis-1.8.8/lib/travis/cli/setup/service.rb:61:in `block in deploy'
            from /home/joshua/.gem/ruby/2.3.0/gems/travis-1.8.8/lib/travis/cli/setup/service.rb:52:in `configure'
            from /home/joshua/.gem/ruby/2.3.0/gems/travis-1.8.8/lib/travis/cli/setup/service.rb:60:in `deploy'
            from /home/joshua/.gem/ruby/2.3.0/gems/travis-1.8.8/lib/travis/cli/setup/releases.rb:11:in `run'
            from /home/joshua/.gem/ruby/2.3.0/gems/travis-1.8.8/lib/travis/cli/setup.rb:55:in `run'
            from /home/joshua/.gem/ruby/2.3.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
            from /home/joshua/.gem/ruby/2.3.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
            from /home/joshua/.gem/ruby/2.3.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
            from /home/joshua/.gem/ruby/2.3.0/bin/travis:22:in `load'
            from /home/joshua/.gem/ruby/2.3.0/bin/travis:22:in `<main>'


    For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
    For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.

**Comment by charlesdaniels** [comment]
Hmm, maybe try creating the oAuth token manually?

[GitHub docs](https://help.github.com/articles/git-automation-with-oauth-tokens/)

**Comment by jyn514** [comment]
Well I have an oAuth token, that's what I put in as the password, it just rejected it on general principles. If you mean put it directly in the .travis.yml file, I'd rather not have people log in as me.

**Comment by jyn514** [comment]
Fixed it. The problem was that I gave my oauth token and not username/password lol

**Comment by charlesdaniels** [comment]
Note that we aught to get the static build working before we can close this issue.

**Comment by jyn514** [comment]
@charlesdaniels looking at https://github.com/pyinstaller/pyinstaller/wiki/FAQ#features, cross-compiling is not supported. I can't see a way to automate this unless we either install wine on the travis docker or run two dockers somehow.

**Comment by charlesdaniels** [comment]
I thought Travis had Windows support?

- - - - 

This email was sent from my smartphone.

**Comment by jyn514** [comment]
Doesn't appear so: https://github.com/travis-ci/travis-ci/issues/216#issuecomment-124138138
as well as documentation: https://docs.travis-ci.com/user/multi-os/

**Comment by charlesdaniels** [comment]
Hmm, it appears a competitor, [AppVeyor](https://www.appveyor.com) has free CI/CD services available for OSS projects, and is Windows based.

On one hand, I don't want the complexity of having two separate CI systems (And I don't even now what that would look like from a release uploading perspective, since I haven't delved into that code yet). On the other hand, lots of people use Windows, and many of them don't have a python interpreter installed.

**Comment by charlesdaniels** [comment]
The WINE idea might also be worth pushing on a bit. Apparently it [has been done befpre](https://github.com/paulfurley/python-windows-packager).

**Comment by jyn514** [comment]
got python running in WINE, working on pyinstaller now

**Comment by jyn514** [comment]
got pyinstaller working. Working on a script for travis now.

**Comment by jyn514** [comment]
trouble in paradise: I used a graphical installer with wine, which likely won't be supported by travis. The only non-graphical installers available are for python3+, so I tried those, but I ran into problems with wine.

Traceback:

    joshua@debian-thinkpad:~/.wine/drive_c/Python35$ wine python
    wine: Call from 0x7b83ae8c to unimplemented function api-ms-win-crt-runtime-l1-1-0.dll._initialize_onexit_table, aborting
    err:module:attach_process_dlls "python35.dll" failed to initialize, aborting
    err:module:LdrInitializeThunk Main exe initialization for L"C:\\Python35\\python.exe" failed, status 80000100

I'm looking at [this](https://unix.stackexchange.com/questions/336759/running-portable-python3-under-wine) stackoverflow post, but I don't know how to use winetricks and I don't particularly want to install wine2 without a package manager. Putting this on the backburner for now.

My script as it currently looks:

    #!/bin/sh
    sudo apt-get install -y wine32 unzip wget
    wine  # configuration files not made until run for first time
    cd ~/.wine/drive_c
    mkdir python36 && cd python36

    # need non-graphical installer i.e. zip file
    # this crashes with python 3.x but succeeds on python2
    # unfortunately, there are no zip files for python2
    wget https://www.python.org/ftp/python/3.6.2/python-3.6.2-embed-win32.zip
    unzip python-3.6.2-embed-win32.zip
    unzip python36.zip

    # pip is not included in python install
    mkdir temp && cd temp
    wget https://bootstrap.pypa.io/get-pip.py
    wine ../python.exe get-pip.py
    cd .. && rm -rf temp

    https://pyinstaller.readthedocs.io/en/stable/requirements.html?highlight=windows
    wine python -m pip install pyinstaller

**Comment by charlesdaniels** [comment]
I have some experience using winetricks. WINE can be quite a bear to get it to work right. I can look into this in a few days after finals. 

Feel free to assign this issue to me.

**Comment by jyn514** [comment]
Got it. Used latest wine version instead of packaged wine. Script:

    #!/bin/sh
    # basics
    sudo apt-get install -y unzip wget

    # only 2.0 runs non-graphical installer
    sudo dpkg --add-architecture i386
    wget -nc https://dl.winehq.org/wine-builds/Release.key
    sudo apt-key add Release.key
    rm Release.key
    echo 'deb https://dl.winehq.org/wine-builds/debian/ debian main' >> /etc/apt/sources.list
    sudo apt-get update
    sudo apt install --install-recommends winehq-stable

    # make config files on first run
    wine
    cd ~/.wine/drive_c
    mkdir python35
    cd python35

    # need non-graphical installer i.e. zip file
    wget https://www.python.org/ftp/python/3.5.0/python-3.5.0-embed-win32.zip
    unzip python-3.5.0-embed-win32.zip
    unzip python35.zip
    rm -f python35.zip python-3.5.0-embed-win32.zip

    # pip is not included in python install
    wget https://bootstrap.pypa.io/get-pip.py
    wine python.exe get-pip.py

    # https://pyinstaller.readthedocs.io/en/stable/requirements.html?highlight=windows
    wine python -m pip install pyinstaller

Once I make it a travis script, we'll be good to go.

Also, this is very much a throwaway script, don't run it too often on your own machine (like me) or you'll end up with 12 duplicate lines in /etc/apt/sources.list

**Comment by charlesdaniels** [comment]
That works to… I’m glad it wound up just being as easy as wgeting the latest WINE release… WINE is a fickle beast. 

good work :)

**Comment by charlesdaniels** [comment]
Oh, I just realized you were actually adding WINE’s Debian repos… I’m surprised that worked, but that’s definitely much better than just wgetting some random binary and running it!

**Comment by jyn514** [comment]
I'd hate to get one giant binary. Just imagine the dependency problems.

**Comment by jyn514** [comment]
Not sure how travis handles scripts. Going to let you handle this bit. Uploading my script now.

**Comment by charlesdaniels** [comment]
> I'd hate to get one giant binary. Just imagine the dependency problems.


Yes, I was about to point out, if you simply wget the latest release and run that, you have no idea what regressions there might be, or if the deps have changed, or so on. 

At least with these method there is some assurance there probably won’t be major regressions or changes. 

> Not sure how travis handles scripts. Going to let you handle this bit. Uploading my script now.

I can certainly do so. To see an example of how to do scripts in Travis, just look at how it runs `do_test.sh` in `.travis.yml`. I don’t mind doing it at all though.

**Comment by jyn514** [comment]
I was imagining it would only run when we choose to release a binary, as opposed to the tests, which run with every change. I'm simply not sure how to set up that condition.

**Comment by charlesdaniels** [comment]
> I was imagining it would only run when we choose to release a binary, as opposed to the tests, which run with every change. I'm simply not sure how to set up that condition.

Ahh, that makes good sense.

I have not had time to dig into release uploading, but I’m sure they have a way to conditionally do things only on tagged commits or something to that effect.

**Comment by jyn514** [comment]
Currently, AppVeyor seems to be our best bet for static executables on windows. Accordingly, we need to 

- remove `scripts/travis.sh`
- set appveyor to upload windows executables on release tags
- set travis to upload linux executables on release tags
- set travis to upload to pypi on release tags

**Comment by jyn514** [comment]
This is almost complete as of https://github.com/charlesdaniels/bitshuffle/commit/6a5a3765013bfe4612b74ab1384a6723c1cd7d56. Before we merge with dev, we need to look at the [appveyor docs](https://www.appveyor.com/docs/packaging-artifacts/) and implement PyPI uploads. We're very close.

**Comment by jyn514** [comment]
Unknown permissions error for appveyor; see [log](https://ci.appveyor.com/project/charlesdaniels/bitshuffle/build/102). Sent email to support, putting it on backburner until they respond. Going to see if I can add conditional uploading for pypi (ideally would upload on *tagged* commits to master).

**Comment by charlesdaniels** [comment]
> Unknown permissions error for appveyor; see log. Sent email to support, putting it on backburner until they respond. Going to see if I can add conditional uploading for pypi (ideally would upload on tagged commits to master).

If conditional uploading winds up not working, we’ll just upload releases manually, as we only want full releases to be uploaded, not release candidates. 

I don’t have any further insight into what’s going on, could be a problem with AppVeyor… hopefully support will be helpful.

**Comment by jyn514** [comment]
If appveyor ends up not working, I believe we can still manage this with wine. The error I was having earlier I fixed with https://github.com/charlesdaniels/bitshuffle/commit/6a5a3765013bfe4612b74ab1384a6723c1cd7d56. The only downside will be that it will take much longer for each static release. 

We can still have Windows testing through appveyor.

**Comment by charlesdaniels** [comment]
To improve the WINE perf, we could try caching the WINE download and WINEPREFIX with Python installed in it. 

I am not opposed to using WINE for this, I just thought AppVeyor would wind up being easier… apparently I was not correct in this respect.

**Comment by jyn514** [comment]
Sorry, hit wrong button. Good news: I got [appveyor working](https://github.com/charlesdaniels/bitshuffle/releases/tag/0.0.1-RC23). Once we get PyPI implemented we'll be ready to merge.

**Comment by jyn514** [comment]
Do we want automatic builds to be tagged as drafts? Currently, appveyor builds are and travis builds are not. I'm fine either way, but it should be consistent across providors. @charlesdaniels

**Comment by charlesdaniels** [comment]
> Do we want automatic builds to be tagged as drafts? Currently, appveyor builds are and travis builds are not. I'm fine either way, but it should be consistent across providors.

I responded to this via email yesterday, but it looks like my response got eaten.

I don't see any reason for automatic builds to be tagged as drafts, unless there is a compelling reason to do so. I was not aware this was happening at all.

**Comment by charlesdaniels** [comment]
#42 has been merged, is there any reason to keep this open @jyn514 ?
