### ISSUE TITLE
Project homepage

### ISSUE THREAD

**Issue by charlesdaniels** [charlesdaniels/bitshuffle#12]
A project homepage should be added. It can be hosted as a static page on [cdaniels.net](http://cdaniels.net) with minimal difficulty.

It should also be added to my [project page](http://cdaniels.net/project.html) also, including a OC mirror.

**Comment by jyn514** [comment]
project link is http://cdaniels.net/project.html, should be http://cdaniels.net/projects.html

**Comment by charlesdaniels** [comment]
Haha, good catch!

**Comment by jyn514** [comment]
You mentioned a while ago that the github page serves this purpose. Closing this.
