### ISSUE TITLE
Exit with error code on error

### ISSUE THREAD

**Issue by jyn514** [charlesdaniels/bitshuffle#14]
Currently most errors are handled with `quit(message)`, which returns success. If used with pipes, this would not have the intended effects.

**Comment by jyn514** [comment]
@charlesdaniels do we have a preference for what error codes should be? Perhaps we could do something as follows:

0 - success
1 - invalid argument or cannot find editor
2 - invalid packet to decode
4 - IO error (file does not exist, etc)
8 - hash mismatch

**Comment by charlesdaniels** [comment]
This is fine with me. 

- - - - 

This email was sent from my smartphone.
