### ISSUE TITLE
Test with both python 2 and 3

### ISSUE THREAD

**Issue by jyn514** [charlesdaniels/bitshuffle#15]
[PyPI metadata](https://github.com/charlesdaniels/bitshuffle/blob/dev/setup.py) states we suppport both 2 and 3. However, tests only currently run on 2. I've manually tested most parts of the application, but it would be nice to automate this.

**Comment by jyn514** [comment]
Done in https://github.com/charlesdaniels/bitshuffle/commit/51f1503e3012b91fcda952ff22a50e944fbd3118

**Comment by charlesdaniels** [comment]
Good catch. I had originally planned to support only Python 3. I didn't even realize the travis tests were in Python 2. Fortunately, the differences between Python 2 and 3 won't matter for this project, so supporting both should be pretty straightforward.
