### ISSUE TITLE
`./setup.py install` doesn't work

### ISSUE THREAD

**Issue by jyn514** [charlesdaniels/bitshuffle#27]
Think it's somehow related to this line: `warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist --
 no Python modules to install`

Full traceback:

    joshua@debian-thinkpad:/usr/local/src/bitshuffle$ ./setup.py install
    running install
    running bdist_egg
    running egg_info
    writing bitshuffle.egg-info/PKG-INFO
    writing top-level names to bitshuffle.egg-info/top_level.txt
    writing dependency_links to bitshuffle.egg-info/dependency_links.txt
    writing entry points to bitshuffle.egg-info/entry_points.txt
    reading manifest file 'bitshuffle.egg-info/SOURCES.txt'
    writing manifest file 'bitshuffle.egg-info/SOURCES.txt'
    installing library code to build/bdist.linux-x86_64/egg
    running install_lib
    warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no Python modules to install

    creating build/bdist.linux-x86_64/egg
    creating build/bdist.linux-x86_64/egg/EGG-INFO
    copying bitshuffle.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying bitshuffle.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying bitshuffle.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying bitshuffle.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    copying bitshuffle.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
    zip_safe flag not set; analyzing archive contents...
    creating 'dist/bitshuffle-0.0.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
    removing 'build/bdist.linux-x86_64/egg' (and everything under it)
    Processing bitshuffle-0.0.1-py2.7.egg
    Removing /usr/local/lib/python2.7/dist-packages/bitshuffle-0.0.1-py2.7.egg
    Copying bitshuffle-0.0.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
    bitshuffle 0.0.1 is already the active version in easy-install.pth
    Installing bitshuffle script to /usr/local/bin

    Installed /usr/local/lib/python2.7/dist-packages/bitshuffle-0.0.1-py2.7.egg
    Processing dependencies for bitshuffle==0.0.1
    Finished processing dependencies for bitshuffle==0.0.1
    joshua@debian-thinkpad:/usr/local/src$ python2 -m bitshuffle
    usage: bitshuffle.py [-h] [--input INPUT] [--output OUTPUT]
                        [--filename FILENAME] [--encode] [--decode] [--version]
                        [--chunksize CHUNKSIZE] [--compresslevel COMPRESSLEVEL]
                        [--editor EDITOR] [--compresstype COMPRESSTYPE]

    optional arguments:
    -h, --help            show this help message and exit
    --input INPUT, -i INPUT
                            Input file. Default is stdin.
    --output OUTPUT, -o OUTPUT
                            Output file. Default is stdout.
    --filename FILENAME, -f FILENAME
                            Set filename to use when encoding explicitly
    --encode, -e          Generate a BitShuffle data packet fromthe input file
    --decode, -d, -D      Extract a BitShuffle data packet.
    --version, -v         Displays the current version of bitshuffle
    --chunksize CHUNKSIZE, -c CHUNKSIZE
                            Chunk size in bytes
    --compresslevel COMPRESSLEVEL, -m COMPRESSLEVEL
                            Compression level when encoding. 1 is lowest, 9 is
                            highest
    --editor EDITOR, -E EDITOR
                            Editor to use for pasting packets
    --compresstype COMPRESSTYPE, -t COMPRESSTYPE
                            Type of compression to use. Defaults to bz2. Ignored
                            if decoding packets. Currently supported: 'bz2',
                            'gzip'
    joshua@debian-thinkpad:/usr/local/src/bitshuffle$ cd ..
    joshua@debian-thinkpad:/usr/local/src$ python2 -m bitshuffle
    /usr/bin/python2: No module named bitshuffle

**Comment by charlesdaniels** [comment]
It installed fine for me on macOS Sierra, but the binary in `$PATH` does not seem to work correctly.

```
(zsh) $ /usr/local/bin/bitshuffle --version
Traceback (most recent call last):
  File "/usr/local/bin/bitshuffle", line 9, in <module>
    load_entry_point('bitshuffle==0.0.1', 'console_scripts', 'bitshuffle')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named bitshuffle
```

Edit 1: All three versions of Python on my system don't see the module either:

```
[cad@leto.local][10:50][~]
(zsh) $ python -m bitshuffle
/usr/bin/python: No module named bitshuffle
[cad@leto.local][10:50][~]
(zsh) $ python2 -m bitshuffle
/usr/local/opt/python/bin/python2.7: No module named bitshuffle
[cad@leto.local][10:51][~]
(zsh) $ python3 -m bitshuffle
/usr/local/opt/python3/bin/python3.6: No module named bitshuffle
```

**Comment by charlesdaniels** [comment]
@jyn514 

Please confirm that 8ce9430aee0a90fc9b2311578d31d2a63468403b has fixed the issue for you. I have assigned the issue to you. If this commit fixes it, please close the issue, otherwise assign it back to me.

**Comment by jyn514** [comment]
Fixed. Thanks for the help.
