### ISSUE TITLE
TravisCI should test setup.py using virtualenv

### ISSUE THREAD

**Issue by charlesdaniels** [charlesdaniels/bitshuffle#29]
What it says on the tin. Just a basic sanity check. Something like `python2 ./setup.py install`, then `/usr/local/bin/bitshufle --version` should exit nonzero. The same for Python 3 would be nice as well, although I don't see a clean way to uninstall it after installing it the first time... could use `pythonX -m bitshuffle.bitshuffle` I suppose, rather than `/usr/local/bin`.

**Comment by charlesdaniels** [comment]
The implementation I have now requires the use of `sudo`. This seems like something that could maybe be done with a virtualenv? I'm not familiar enough with virtualenvs, so I need to dig into that a bit more.

**Comment by charlesdaniels** [comment]
Tests are implementing and passing as of 0c0f1a4ec1cfb7bb31439a00be1ed97f8ec2cfc6. Leaving this open until the virtualenv thing is investigated.

**Comment by jyn514** [comment]
This ended up being a lot easier than I expected; all you do is replace `python setup.py install` with `pip install .`

**Comment by jyn514** [comment]
Addressed in https://github.com/charlesdaniels/bitshuffle/pull/52, waiting on a review to merge
