### ISSUE TITLE
Make readpath portable

### ISSUE THREAD

**Issue by jyn514** [charlesdaniels/bitshuffle#33]
[`readlink -e`](https://github.com/charlesdaniels/bitshuffle/blob/dev/scripts/test_argument_options.sh#L10) is not supported on MacOS and various other OSes. Possible solution in Charles' [toolchest](https://github.com/charlesdaniels/toolchest/blob/master/lib/realpath.lib).

**Comment by charlesdaniels** [comment]
resolved in 1332425
