### ISSUE TITLE
Code Quality Checks with ShellCheck

### ISSUE THREAD

**Issue by charlesdaniels** [charlesdaniels/bitshuffle#36]
We have enough automation scripts that we should probably do automated code quality checks on them. I have used [ShellCheck](https://www.shellcheck.net) for other projects and found that it worked really well. 

This should be added to the pre-commit checks, and also the test suite that TravisCI runs.

**Comment by jyn514** [comment]
Implemented in https://github.com/charlesdaniels/bitshuffle/pull/41.
