### ISSUE TITLE
Add Unicode support

### ISSUE THREAD

**Issue by jyn514** [charlesdaniels/bitshuffle#45]
We specifically preclude unicode support in `encode_packet` with the line `data = data.decode(encoding="ascii")`. Since unicode is ascii-compatible, this *should* be as simple as changing `encoding="ascii"` to `encoding="unicode"`.

**Comment by charlesdaniels** [comment]
Agreed. This looks like the right thing to do. 

- - - - 

This email was sent from my smartphone.

**Comment by jyn514** [comment]
Added in https://github.com/charlesdaniels/bitshuffle/commit/7330dede8969f92fb814f24a7a737e2b152786ec, along with unit test
