### ISSUE TITLE
Add option to edit message

### ISSUE THREAD

**Issue by jyn514** [charlesdaniels/bitshuffle#47]
Currently, the message is hardcoded in the `encode_packet` method:

msg = "This is encoded with BitShuffle, which you can download " + \
        "from https://github.com/charlesdaniels/bitshuffle"

It would be nice to specify a message from the command line.

**Comment by charlesdaniels** [comment]
Yes, I’ve been meaning to do something of this sort, but I never got around to opening an issue.

**Comment by jyn514** [comment]
Closed in https://github.com/charlesdaniels/bitshuffle/pull/49
