### ISSUE TITLE
--version flag should be added

### ISSUE THREAD

**Issue by charlesdaniels** [charlesdaniels/bitshuffle#7]
After the first release (when that happens), it will be useful to have a `--version` flag. Example:

```
>>> import argparse
>>> parser = argparse.ArgumentParser(prog='PROG')
>>> parser.add_argument('--version', action='version', version='%(prog)s 2.0')
>>> parser.parse_args(['--version'])
PROG 2.0
```

[source](https://docs.python.org/3/library/argparse.html)

**Comment by jyn514** [comment]
Added in https://github.com/charlesdaniels/bitshuffle/commit/998b11f51d9b73e10d70790aadd1ed30e9b23e47

**Comment by charlesdaniels** [comment]
cross reference  1060d804d3b83f259714b07aeae0360ee33653e3
